apiVersion: v1
kind: ServiceAccount
metadata:
  name: cs3-portal
  namespace: cs3-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cs3-portal-role
  namespace: cs3-prod
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cs3-portal-rolebinding
  namespace: cs3-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cs3-portal-role
subjects:
- kind: ServiceAccount
  name: cs3-portal
  namespace: cs3-prod
