apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cs3-portal-ingress
  namespace: cs3-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - portal.innovatech.local
    secretName: portal-tls
  rules:
  - host: portal.innovatech.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cs3-portal-svc
            port:
              number: 80
