apiVersion: v1
kind: Service
metadata:
  name: cs3-portal-svc
spec:
  selector:
    app: cs3-portal
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: portal-allow-ingress
spec:
  podSelector:
    matchLabels:
      app: cs3-portal
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 5000
